Numpy Tutorial

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,3,4],[5,6,7],[1,5,8]])

In [3]:
print(arr)

[[1 3 4]
 [5 6 7]
 [1 5 8]]


In [4]:
print(arr[0])

[1 3 4]


In [5]:
print(arr[0][1])

3


In [6]:
arr[0][1]=10

In [7]:
arr

array([[ 1, 10,  4],
       [ 5,  6,  7],
       [ 1,  5,  8]])

In [8]:
arrzero=np.zeros((2,4))

In [9]:
arrzero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arrrange=np.arange(10)

In [11]:
arrrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arrrange[3]

np.int64(3)

In [13]:
arrrange.dtype

dtype('int64')

In [14]:
arrl=np.linspace(1,1000000,5000)

In [15]:
arrl

array([1.00000000e+00, 2.01039808e+02, 4.01079616e+02, ...,
       9.99599920e+05, 9.99799960e+05, 1.00000000e+06], shape=(5000,))

In [16]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [17]:
idn=np.identity(10)

In [18]:
idn

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
mat2=np.array([[11,22,33],[44,55,66],[77,88,99]])
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matX=mat1*mat2

In [24]:
matX

array([[ 11,  44,  99],
       [176, 275, 396],
       [539, 704, 891]])

In [25]:
matX

array([[ 11,  44,  99],
       [176, 275, 396],
       [539, 704, 891]])

Axis is use as row or column where axis=0 is row and axis=1 is column

In [26]:
matX.sum(axis=0)

array([ 726, 1023, 1386])

In [27]:
matX.sum(axis=1)

array([ 154,  847, 2134])

In [30]:
matX

array([[ 11,  44,  99],
       [176, 275, 396],
       [539, 704, 891]])

In [31]:
matX.T

array([[ 11, 176, 539],
       [ 44, 275, 704],
       [ 99, 396, 891]])

In [33]:
matX.argmax()

np.int64(8)

In [34]:
ar=matX

In [35]:
ar.argmax()

np.int64(8)

In [38]:
ar.argmin()

np.int64(0)

In [39]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [40]:
matX.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [41]:
matX.tolist()

[[11, 44, 99], [176, 275, 396], [539, 704, 891]]